# Generated by Django 3.0.6 on 2020-05-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20200515_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_group',
        ),
        migrations.AddField(
            model_name='exercise',
            name='ppl',
            field=models.CharField(choices=[('Push', 'Push'), ('Pull', 'Pull'), ('Legs', 'Legs')], default='NA', max_length=4),
        ),
    ]
