# Generated by Django 3.0.6 on 2020-05-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20200515_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.ManyToManyField(related_name='exercises', to='workouts.MuscleGroup'),
        ),
    ]
