# Generated by Django 3.0.6 on 2020-06-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_exercise_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='muscle_group',
            new_name='musclegroups',
        ),
    ]
