# Generated by Django 3.0.6 on 2020-06-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_auto_20200603_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='ppl',
            new_name='push_pull_legs',
        ),
    ]
