# Generated by Django 3.1 on 2020-08-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_auto_20200619_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='musclegroups',
            field=models.ManyToManyField(to='workouts.MuscleGroup'),
        ),
    ]
